module Conversiones 
	(numToCiudad,
	ciudadToNum
	)where

numToCiudad :: Int -> String
numToCiudad 1 = "Albany, NY"                  
numToCiudad 2 = "Albuquerque, NM"               
numToCiudad 3 = "Atlanta, GA (Metro Area)"      
numToCiudad 4 = "Atlantic City, NJ"             
numToCiudad 5 = "Austin, TX"                    
numToCiudad 6 = "Bellingham, WA"                
numToCiudad 7 = "Birmingham, AL"                
numToCiudad 8 = "Boise, ID"                     
numToCiudad 9 = "Boston, MA (Metro Area)"       
numToCiudad 10 = "Buffalo, NY"               
numToCiudad 11 = "Burlington, VT"            
numToCiudad 12 = "Charleston, SC"            
numToCiudad 13 = "Charlotte, NC"             
numToCiudad 14 = "Chicago, IL"               
numToCiudad 15 = "Cincinnati, KY"            
numToCiudad 16 = "Cleveland, OH (Metro Area)"
numToCiudad 17 = "Colorado Springs, CO"      
numToCiudad 18 = "Columbia, SC"              
numToCiudad 19 = "Columbus, OH"              
numToCiudad 20 = "Corpus Christi, TX"        
numToCiudad 21 = "Dallas, TX"                
numToCiudad 22 = "Dayton, OH"                
numToCiudad 23 = "Denver, CO"                
numToCiudad 24 = "Des Moines, IA"            
numToCiudad 25 = "Detroit, MI"                  
numToCiudad 26 = "El Paso, TX"                  
numToCiudad 27 = "Eugene, OR"                   
numToCiudad 28 = "Flint, MI"                    
numToCiudad 29 = "Fort Myers, FL"               
numToCiudad 30 = "Fresno, CA"                   
numToCiudad 31 = "Grand Rapids, MI"             
numToCiudad 32 = "Greensboro/High Point, NC"    
numToCiudad 33 = "Hartford, CT"                 
numToCiudad 34 = "Houston, TX"                  
numToCiudad 35 = "Huntsville, AL"               
numToCiudad 36 = "Indianapolis, IN"             
numToCiudad 37 = "Jacksonville, FL"             
numToCiudad 38 = "Kansas City, MO"              
numToCiudad 39 = "Key West, FL"                 
numToCiudad 40 = "Las Vegas, NV"                
numToCiudad 41 = "Los Angeles, CA (Metro Area)" 
numToCiudad 42 = "Louisville, KY"               
numToCiudad 43 = "Medford, OR"                  
numToCiudad 44 = "Memphis, TN"                  
numToCiudad 45 = "Miami, FL (Metro Area)"       
numToCiudad 46 = "Milwaukee, WI"                
numToCiudad 47 = "Minneapolis, MN"              
numToCiudad 48 = "Myrtle Beach, SC"              
numToCiudad 49 = "Nashville, TN"                 
numToCiudad 50 = "New Orleans, LA"               
numToCiudad 51 = "New York City, NY (Metro Area)"
numToCiudad 52 = "Oklahoma City, OK"             
numToCiudad 53 = "Omaha, NE"                     
numToCiudad 54 = "Orlando, FL"                   
numToCiudad 55 = "Philadelphia, PA"              
numToCiudad 56 = "Phoenix, AZ"                   
numToCiudad 57 = "Pittsburgh, PA"                
numToCiudad 58 = "Portland, OR"                  
numToCiudad 59 = "Sacramento, CA"                
numToCiudad 60 = "San Antonio, TX"               
numToCiudad 61 = "San Diego, CA"                 
numToCiudad 62 = "San Francisco, CA (Metro Area)"
numToCiudad 63 = "Seattle, WA"                   
numToCiudad 64 = "Sioux Falls, SD"               
numToCiudad 65 = "Spokane, WA"                   
numToCiudad 66 = "St. Louis, MO"                 
numToCiudad 67 = "Tampa, FL (Metro Area)"        
numToCiudad 68 = "Tucson, AZ"                    
numToCiudad 69 = "Washington, DC (Metro Area)"   
numToCiudad 70 = "West Palm Beach/Palm Beach, FL"
numToCiudad x  = show x :: String


ciudadToNum :: String -> Int
ciudadToNum "Albany, NY"                    = 1
ciudadToNum "Albuquerque, NM"               = 2
ciudadToNum "Atlanta, GA (Metro Area)"      = 3
ciudadToNum "Atlantic City, NJ"             = 4
ciudadToNum "Austin, TX"                    = 5
ciudadToNum "Bellingham, WA"                = 6
ciudadToNum "Birmingham, AL"                = 7
ciudadToNum "Boise, ID"                     = 8
ciudadToNum "Boston, MA (Metro Area)"       = 9
ciudadToNum "Buffalo, NY"                   = 10
ciudadToNum "Burlington, VT"                = 11
ciudadToNum "Charleston, SC"                = 12
ciudadToNum "Charlotte, NC"                 = 13
ciudadToNum "Chicago, IL"                   = 14
ciudadToNum "Cincinnati, KY"                = 15
ciudadToNum "Cleveland, OH (Metro Area)"    = 16
ciudadToNum "Colorado Springs, CO"          = 17
ciudadToNum "Columbia, SC"                  = 18
ciudadToNum "Columbus, OH"                  = 19
ciudadToNum "Corpus Christi, TX"            = 20
ciudadToNum "Dallas, TX"                    = 21
ciudadToNum "Dayton, OH"                    = 22
ciudadToNum "Denver, CO"                    = 23
ciudadToNum "Des Moines, IA"                = 24
ciudadToNum "Detroit, MI"                   = 25
ciudadToNum "El Paso, TX"                   = 26
ciudadToNum "Eugene, OR"                    = 27
ciudadToNum "Flint, MI"                     = 28
ciudadToNum "Fort Myers, FL"                = 29
ciudadToNum "Fresno, CA"                    = 30
ciudadToNum "Grand Rapids, MI"              = 31
ciudadToNum "Greensboro/High Point, NC"     = 32
ciudadToNum "Hartford, CT"                  = 33
ciudadToNum "Houston, TX"                   = 34
ciudadToNum "Huntsville, AL"                = 35
ciudadToNum "Indianapolis, IN"              = 36
ciudadToNum "Jacksonville, FL"              = 37
ciudadToNum "Kansas City, MO"               = 38
ciudadToNum "Key West, FL"                  = 39
ciudadToNum "Las Vegas, NV"                 = 40
ciudadToNum "Los Angeles, CA (Metro Area)"  = 41
ciudadToNum "Louisville, KY"                = 42
ciudadToNum "Medford, OR"                   = 43
ciudadToNum "Memphis, TN"                   = 44
ciudadToNum "Miami, FL (Metro Area)"        = 45
ciudadToNum "Milwaukee, WI"                 = 46
ciudadToNum "Minneapolis, MN"               = 47
ciudadToNum "Myrtle Beach, SC"              = 48
ciudadToNum "Nashville, TN"                 = 49
ciudadToNum "New Orleans, LA"               = 50
ciudadToNum "New York City, NY (Metro Area)"= 51
ciudadToNum "Oklahoma City, OK"             = 52
ciudadToNum "Omaha, NE"                     = 53
ciudadToNum "Orlando, FL"                   = 54
ciudadToNum "Philadelphia, PA"              = 55
ciudadToNum "Phoenix, AZ"                   = 56
ciudadToNum "Pittsburgh, PA"                = 57
ciudadToNum "Portland, OR"                  = 58
ciudadToNum "Sacramento, CA"                = 59
ciudadToNum "San Antonio, TX"               = 60
ciudadToNum "San Diego, CA"                 = 61
ciudadToNum "San Francisco, CA (Metro Area)"= 62
ciudadToNum "Seattle, WA"                   = 63
ciudadToNum "Sioux Falls, SD"               = 64
ciudadToNum "Spokane, WA"                   = 65
ciudadToNum "St. Louis, MO"                 = 66
ciudadToNum "Tampa, FL (Metro Area)"        = 67
ciudadToNum "Tucson, AZ"                    = 68
ciudadToNum "Washington, DC (Metro Area)"   = 69
ciudadToNum "West Palm Beach/Palm Beach, FL"= 70
ciudadToNum x= read x :: Int